### ISSUE TITLE
crashes during installation

### ISSUE THREAD

**Issue by paulperegud** [cpoppema/pass-browser-chrome#3]
Crashes during installation.

Error message:
````
Could not install package: 
'UTILITY_PROCESS_CRASHED_WHILE_TRYING_TO_INSTALL'. 
Could not install package because a utility process crashed.
Try restarting Chrome and trying again.
````
Source: https://chrome.google.com/webstore/detail/pass-browser-chrome/ncoadlppaciemlepmdmdnecjlfmbidcd?hl=en-US
Browser: Version 49.0.2623.108 Ubuntu 15.10 (64-bit)
Other extensions: 
* Signal Private Messenger 0.12.2 (id: bikioccmkafdpakkkcpdbppfkghcmihk)
* Unity WebApps Chromium extension 3.2 (id: pmoflmbbcfgacopiikdcpmbiellfihdg)

NOTE: does not crash on fresh profile (with Signal not installed).

**Comment by cpoppema** [comment]
Hello @paulperegud, thanks for taking the time to report!

I'm currently in the process of setting up a VM to see if I'm able to re-produce and find a solution.

Can you please post your kernel version (type ``uname -r`` in a terminal) and tell me if you're using either Google's Chrome or Chromium ? I can't really trust the error message on this (i.e. sometimes the browser says "Chrome" even when running Chromium).

**Comment by cpoppema** [comment]
So far it works inside my virtual machine, what I did was install ubuntu-15.10 64-bit inside virtualbox on a debian 8 machine.

Ubuntu 15.10 ships with kernel 4.2.0-16-generic. I installed Google _Chromium_ 49.0.2623.108 using debian-packages from http://archive.ubuntu.com/ubuntu/pool/universe/c/chromium-browser/. Files I installed using `dpkg -i` in one command after downloading:

http://archive.ubuntu.com/ubuntu/pool/universe/c/chromium-browser/chromium-browser_49.0.2623.108-0ubuntu1.1233_amd64.deb

http://archive.ubuntu.com/ubuntu/pool/universe/c/chromium-browser/chromium-codecs-ffmpeg-extra_49.0.2623.108-0ubuntu1.1233_amd64.deb

http://archive.ubuntu.com/ubuntu/pool/universe/c/chromium-browser/chromium-codecs-ffmpeg_49.0.2623.108-0ubuntu1.1233_amd64.deb

Although the last one looked unnecessary:
```
dpkg: yes, will remove chromium-codecs-ffmpeg in favour of chromium-codecs-ffmpeg-extra
```

After this I started the browser and immediately installed Signal Private Messenger (v0.12.5) from the webstore: https://chrome.google.com/webstore/detail/signal-private-messenger/bikioccmkafdpakkkcpdbppfkghcmihk, closed the Signal-window that opened automatically and installed pass-browser-chrome (v0.4.0) next. This happened without any error messages showing up.

**Comment by paulperegud** [comment]
> kernel version

$ uname -r
4.2.0-36-generic

> Google's Chrome or Chromium ?

Chromium

The only actual difference in our setups was the fact that I was using Signal v0.12.2 instead of v0.12.5. Not sure why Chromium has not updated it to new version automatically.

I've removed Signal and added it from Store once again. Next I added pass-browser-chrome from Store - and it works!

Root cause of this error seems to be related to particular version Signal. Maybe too obscure to put more time into it. Your call.

**Comment by cpoppema** [comment]
I'm glad it now works. After spending some time searching for others that also experienced this error message, there seems to be a wide variety of possible causes on different platforms. Looks like it is an unresolved issue with Google Chromium: [#251761](https://bugs.chromium.org/p/chromium/issues/detail?id=251761).
